package ee.ut.cs.pathbuddy.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single trip record in the local Room database.
 * This is the storage-level representation of a trip.
 *
 * @param id The unique identifier for the trip, auto-generated by the database.
 * @param destination The primary destination of the trip (e.g., "Paris, France").
 * @param startDate The start date of the trip in ISO format (YYYY-MM-DD).
 * @param endDate The end date of the trip in ISO format (YYYY-MM-DD).
 * @param interests A comma-separated string of user interests for the trip.
 * @param budgetCategory An optional category for the trip's budget (e.g., "Budget", "Luxury").
 */
@Entity(tableName = "trips")
data class TripEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val destination: String,
    val startDate: String,
    val endDate: String,
    val interests: String,
    val budgetCategory: String?
)